format = "$kubernetes$custom\n[>](green) "
command_timeout = 1000

[kubernetes]
format = '[$symbol$context]($style) '
disabled=false

[nodejs]
disabled=true

[aws]
disabled=true

[git_branch]
disabled = true

[git_status]
disabled = true

[directory]
disabled = true

[custom.stack]
command = "/Users/philbrockman/.dotfiles/scripts/stack-prompt.sh"
when = "REPO=$(basename $(git rev-parse --show-toplevel 2>/dev/null) 2>/dev/null) && (test -f ~/.local/share/stack/$REPO/stack || test -f ~/.local/share/stack/$REPO/convention)"
format = "[$output]($style) "
style = "purple"
description = "Git stack position"

[custom.git_simple]
command = "git branch --show-current"
when = "REPO=$(basename $(git rev-parse --show-toplevel 2>/dev/null) 2>/dev/null); test ! -f ~/.local/share/stack/$REPO/stack && test ! -f ~/.local/share/stack/$REPO/convention"
format = "[$output]($style) "
style = "bold purple"
description = "Git branch when not in stack"
