[kubernetes]
disabled=false

[nodejs]
disabled=true

[aws]
disabled=true

[custom.stack]
command = "~/.dotfiles/scripts/stack-prompt.sh"
when = "test -f .stack"
format = "[$output]($style) "
style = "purple"
