format = "$kubernetes$custom\n[>](green) "
command_timeout = 1000

[kubernetes]
format = '[$symbol$context]($style) '
disabled=false

[nodejs]
disabled=true

[aws]
disabled=true

[git_branch]
disabled = true

[git_status]
disabled = true

[directory]
disabled = true

[custom.git]
command = "/Users/philbrockman/.dotfiles/scripts/stack-prompt.sh"
when = "git rev-parse --show-toplevel 2>/dev/null"
format = "[$output]($style) "
style = "purple"
description = "Git branch with stack position from git-town"
